name: Make documentation for dev branch

on: 
  push:
    branches: 
      - dev  

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:  
  docs:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        shell: bash
        working-directory: ${{runner.workspace}}/build
        # Note the current convention is to use the -S and -B options here to specify source 
        # and build directories, but this is only available with CMake 3.13 and higher.  
        # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Make documentation
        working-directory: ${{runner.workspace}}/build
        run : make doc

      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          repository: 'gh-pages'
          path : '${{runner.workspace}}/gh-pages'

      - name: Add new exported documentation and push to gh-pages branch
        run: |
          cp -r ${{runner.workspace}}/build/docs/doxygen/html ${{runner.workspace}}/gh-pages/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Automatically updated the wiki" && git push
